---
title: "cm_103"
author: "Ryan"
date: "10/31/2017"
output: html_document
---

## vectors

atomic vectors - all elements are of the same type

```{r}
(v_log <- c(TRUE, FALSE, FALSE, TRUE))
v_char <- c("years", "days")
v_doub <- 1:4 *1.2
typeof(v_doub)
(v_char <- letters(1:4))
typeof <- v_char

v_char[c(FALSE, FALSE, TRUE, TRUE)]

v_char[v_log]

```

## Index by position

```{r}
v_doub[2:3]
v_doub[1]

v_char[-4]
```


```{r}
v_doub_copy <- v_doub
str(v_doub_copy)

v_doub_copy[3] <- "uhoh"

str(v_doub_copy)
```


## lists

```{r}
(x <- list(1:3, c("four", "five")))

(y <- list(logical = TRUE, integer = 4L, double = 4 *1.2, character = "character"))

(z <- list(letters[26:22], transcendental = c(pi, exp(1)), f = function(x) x^2))

```


## Challenge - pull out 2 and 3 elements in y, in z pull out all transcend numbers

```{r}
y[2:3]

z$transcendental

typeof(z["transcendental"])
typeof(z[["transcendental"]])

y[["double"]]
```
List x3?


## consider how to square the integers 1 to n

```{r}
n <- 5
```

```{r}
res <- rep(NA_integer_, n)
for(i in seq_len(n)) {
  res[i] <- i^2
}

# you could also do
(1:n)^2
```

```{r}
exp(v_doub)
(l_doub <- as.list(v_doub))
exp(l_doub)
```

```{r}
library(purrr)

map_dbl(l_doub, exp)

```

```{r}
library(stringr)
fruit
```

## Use map and stringr function to split fruits that have 2 words in them into two separate characters

```{r}
fruit %>% 
  map(str_split, " ")

fruit %>% 
  map_chr(str_to_upper)
```

```{r}
library(repurrrsive)
library(listviewer)
library(purrr)

str(gh_users)
```


```{r}
jsonedit(gh_users)

map(gh_users, "login")

gh_users %>% 
  map(18)


x <- map(gh_users, `[`, c("login", "name", "id", "location"))
x

```









